"""add_penalty_acceptance_other_deductions_compensation_to_sales

Revision ID: 6097ed76f0a0
Revises: 8b197ce38ecb
Create Date: 2026-03-18 10:34:30.992242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6097ed76f0a0'
down_revision: Union[str, None] = '8b197ce38ecb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('penalty', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False))
    op.add_column('sales', sa.Column('acceptance', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False))
    op.add_column('sales', sa.Column('other_deductions', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False))
    op.add_column('sales', sa.Column('compensation', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales', 'compensation')
    op.drop_column('sales', 'other_deductions')
    op.drop_column('sales', 'acceptance')
    op.drop_column('sales', 'penalty')
    # ### end Alembic commands ###
