"""add_acquiring_to_sku_daily_expenses

Revision ID: 7386daea6621
Revises: c3d4e5f6a7b8
Create Date: 2026-03-19 12:07:33.194613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7386daea6621'
down_revision: Union[str, None] = 'c3d4e5f6a7b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sku_daily_expenses', sa.Column('acquiring', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sku_daily_expenses', 'acquiring')
    # ### end Alembic commands ###
