"""add_lamoda_integration_type

Revision ID: 876ea47a58ba
Revises: d5e3a1c8f720
Create Date: 2026-03-15 20:32:59.513423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '876ea47a58ba'
down_revision: Union[str, None] = 'd5e3a1c8f720'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pnl_records_period', table_name='pnl_records')
    op.drop_table('pnl_records')
    op.alter_column('ad_metrics', 'search_budget',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('ad_metrics', 'search_impressions',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('ad_metrics', 'search_clicks',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('ad_metrics', 'search_orders',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('ad_metrics', 'recommend_budget',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('ad_metrics', 'recommend_impressions',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('ad_metrics', 'recommend_clicks',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('ad_metrics', 'recommend_orders',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('card_stats', 'open_card_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('card_stats', 'add_to_cart_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('card_stats', 'orders_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('sku_cost_history', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_index('ix_sku_cost_history_period', table_name='sku_cost_history')
    op.alter_column('stocks', 'in_way_to_client',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('stocks', 'in_way_from_client',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_constraint('stocks_sku_wh_date_unique', 'stocks', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('stocks_sku_wh_date_unique', 'stocks', ['sku_id', 'warehouse_id', 'date'])
    op.alter_column('stocks', 'in_way_from_client',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('stocks', 'in_way_to_client',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.create_index('ix_sku_cost_history_period', 'sku_cost_history', ['sku_id', 'effective_from'], unique=False)
    op.alter_column('sku_cost_history', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('card_stats', 'orders_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('card_stats', 'add_to_cart_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('card_stats', 'open_card_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('ad_metrics', 'recommend_orders',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('ad_metrics', 'recommend_clicks',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('ad_metrics', 'recommend_impressions',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('ad_metrics', 'recommend_budget',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('ad_metrics', 'search_orders',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('ad_metrics', 'search_clicks',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('ad_metrics', 'search_impressions',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('ad_metrics', 'search_budget',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.create_table('pnl_records',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('period', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('line_item', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('parent_line', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('amount', sa.NUMERIC(precision=18, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('pct_of_revenue', sa.NUMERIC(precision=8, scale=4), autoincrement=False, nullable=True),
    sa.Column('sort_order', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='pnl_records_pkey')
    )
    op.create_index('ix_pnl_records_period', 'pnl_records', ['period'], unique=False)
    # ### end Alembic commands ###
