"""add_ads_api_key_to_integrations

Revision ID: 8b197ce38ecb
Revises: 3b038fa6e25f
Create Date: 2026-03-16 09:29:43.578712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8b197ce38ecb'
down_revision: Union[str, None] = '3b038fa6e25f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('integrations', sa.Column('ads_api_key', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('integrations', 'ads_api_key')
    # ### end Alembic commands ###
