"""add_storage_costs_table

Revision ID: 9a76ea440240
Revises: aca2c186c689
Create Date: 2026-03-13 20:43:12.582817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9a76ea440240'
down_revision: Union[str, None] = 'aca2c186c689'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('storage_costs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('warehouse_name', sa.String(length=200), nullable=True),
    sa.Column('cost', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('qty_on_warehouse', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('storage_costs')
    # ### end Alembic commands ###
