"""add_price_after_spp_spp_pct_to_orders

Revision ID: aca2c186c689
Revises: 
Create Date: 2026-03-13 20:10:45.609547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'aca2c186c689'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('price_after_spp', sa.Numeric(precision=12, scale=2), nullable=False, server_default='0'))
    op.add_column('orders', sa.Column('spp_pct', sa.Numeric(precision=5, scale=2), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'spp_pct')
    op.drop_column('orders', 'price_after_spp')
    # ### end Alembic commands ###
