"""add_sku_daily_expenses_table

Revision ID: b5d7f87dc8e0
Revises: 6097ed76f0a0
Create Date: 2026-03-18 11:06:19.859682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b5d7f87dc8e0'
down_revision: Union[str, None] = '6097ed76f0a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sku_daily_expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku_id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('sale_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('commission', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('logistics', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('storage', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('penalty', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('acceptance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('other_deductions', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('compensation', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('return_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('items_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku_id', 'channel_id', 'date', name='uq_sku_daily_expense')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sku_daily_expenses')
    # ### end Alembic commands ###
